// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ca-central-1",
    "aws_content_delivery_bucket": "hsseven-20181026092108--hostingbucket",
    "aws_content_delivery_bucket_region": "ca-central-1",
    "aws_content_delivery_url": "http://hsseven-20181026092108--hostingbucket.s3-website.ca-central-1.amazonaws.com"
};


export default awsmobile;
